### ISSUE TITLE
Mixed https/http content (http favicon, urls) on https://getsatisfaction.com/eternagame/

### ISSUE THREAD

**Issue by ValZapod** [eternagame/eternagame.org#1]
```
<link rel="shortcut icon" href="http://eternagame.org/favicon.ico" type="image/x-icon">
<a href="http://www.eternagame.org" target="_blank">Website</a> 
```
(//www.eternagame.org)
http://twitter.com/eternaGame 
http://www.cmu.edu
http://www.stanford.edu
http://www.facebook.com/pages/EteRNA/164108823617587
http://getsatisfaction.com

**Comment by luxaritas** [comment]
Thanks for the heads up - I've updated the forum favicon to correctly use HTTPS - let me know if you have any other concerns

**Comment by ValZapod** [comment]
@luxaritas Still one http://getsatisfaction.com present. Also you may want one warning solved in chrome console (F12). 
`[Deprecation]The behavior that Selection.addRange() merges existing Range and the specified Range was removed.`
That was fast, cool))

**Comment by luxaritas** [comment]
Both of those aren't anything I can do about. The prior things were links I set, but those are things written by GetSatisfaction (our forum provider) itself. Nothing I can do, but I'll file a ticket with them.

**Comment by ValZapod** [comment]
Still good. I mean that favicon will not even boot in Chrome 78, unless you permit it... https://www.wpbeginner.com/news/google-chrome-will-block-mixed-content-are-you-ready-for-it/
This article is bad, because this mixed content was already in chrome 77... But is has cool pictures.
