### ISSUE TITLE
allows user to follow other users

### ISSUE THREAD

**Issue by agarg5** [eternagame/eternagame.org#103]

**Comment by luxaritas** [comment]
Following on the legacy site doesn't do anything - nothing on the backend triggers notifications when you follow a user

**Comment by agarg5** [comment]
Ok will keep this in mind

**Comment by agarg5** [comment]
@ktamas77 could you please fill out the param data in the respective endpoints on swagger?: [follow](https://eternagame.org/home/swagger/index.html#/default/get_get__type_follow), [follows](https://eternagame.org/home/swagger/index.html#/default/get_get__type_follows) with info such as an example of `follow_type` and descriptions for each endpoint

**Comment by ktamas77** [comment]
Related: https://app.clubhouse.io/vital-mind-media/story/1026/openapi-extension-with-follow-related-endpoints

**Comment by ktamas77** [comment]
OpenAPI documentation extended with available enum types: 
`"node", "user", "group"`

example: https://eternagame.org/get/?type=follows&id=1&follow_type=user

**Comment by guyguy2001** [comment]
Can we close this with the PR?
