### ISSUE TITLE
Don't show preloader when there isn't more content to load

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#106]
Instead we should have some sort of indicator that we've hit the end of available content (eg, "That's all we have - try searching for something else!"

**Comment by agarg5** [comment]
@luxaritas this should not be an issue anymore. We show nothing if the user has already fetched all available content with the preloader. Please let me know if anything else is needed on this one.

![2020-05-18 12 02 07](https://user-images.githubusercontent.com/45175645/82203140-2ef54900-9903-11ea-9608-9c69e7ecabf4.gif)
