### ISSUE TITLE
Ensure notifications support all possible types

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#110]
Basically we should just walk through the [legacy code](https://github.com/eternagame/website/blob/master/frontend/coffee/eterna/builder-me.coffee) and make sure each individual case is handled - that's the most reliable option I can think of. This will probably fall on me since I have at least a rudimentary understanding of how that code works, and it's a bit of a mess

**Comment by agarg5** [comment]
@luxaritas To save you time, if you can provide an example of data returned from the API for the other notification types, I can implement this.

**Comment by luxaritas** [comment]
The types have now been fully fleshed out for this. Remaining are:
- "Simple" group messages that do not have the group name in them (used for invites)
- Group messages (admin broadcasts)
- Group comments
- Lab reward notifications (design + vote)

**Comment by luxaritas** [comment]
I had implemented most of this before, but there were still issues with group-related notifications - #236 should be the last bit that's needed here
