### ISSUE TITLE
Users can trigger a grey carousel panel if they switch panels too quickly

### ISSUE THREAD

**Issue by guyguy2001** [eternagame/eternagame.org#111]
![image](https://user-images.githubusercontent.com/6932278/82152561-be9ae900-986a-11ea-8fd1-645f1b38dbc1.png)
This happens if you click a page button at the bottom of the carousel, and then click two other buttons before it finishes scrolling to the panel you selected.
The panel you scroll out of becomes grey, so when the scrolling animation is done you don't see the grey panel anymore.

**Comment by guyguy2001** [comment]
This seems to either be a bug in BootstrapVue or in Boostrap (I can reproduce this on https://bootstrap-vue.org/docs/components/carousel). I'll file an issue there tomorrow.

**Comment by guyguy2001** [comment]
I finally posted it on their github - 
https://github.com/bootstrap-vue/bootstrap-vue/issues/5810

**Comment by guyguy2001** [comment]
Fixed in https://github.com/bootstrap-vue/bootstrap-vue/pull/5845; An npm install should be enough.

**Comment by luxaritas** [comment]
Resolved
