### ISSUE TITLE
Improve linking in activity dropdown

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#113]
EG, when a notification is about a comment, it should link to the appropriate node being commented on. I don't think the current links for regular message notifications work either (where it's supposed to scroll to the appropriate notification in the feed)

**Comment by agarg5** [comment]
got this working

![2020-05-18 11 44 47](https://user-images.githubusercontent.com/45175645/82198742-08341400-98fd-11ea-885c-e9600ae943c2.gif)
