### ISSUE TITLE
add energy model to puzzles

### ISSUE THREAD

**Issue by agarg5** [eternagame/eternagame.org#115]
@ktamas77 where can we get the data for the energy model? 
![image](https://user-images.githubusercontent.com/45175645/82194137-a07aca80-98f6-11ea-981b-e64eef8b3abe.png)

@sharife
1.  I notice sometimes the state icon has arrows around it such as for `state=3`
![image](https://user-images.githubusercontent.com/45175645/82194185-b1c3d700-98f6-11ea-8445-4b6b04caade0.png) and other times doesn't such as for `state=4`
![image](https://user-images.githubusercontent.com/45175645/82194226-bee0c600-98f6-11ea-8659-d40ca047205b.png). What are the rules around when the arrows should be present?

2. It like when the energy model is present, the number of people who cleared the puzzle doesn't need to be shown, correct?

**Comment by sharife** [comment]
Thanks! 
1. We decided to change the icon to include the arrows (in all instances).
2. We replaced the number of solvers with the points display. All puzzles use an energy model. The only variable element is whether or not there are switch states (if there is only one state, do not display the switch icon/number).

**Comment by ktamas77** [comment]
corresponding ticket: https://app.clubhouse.io/vital-mind-media/story/937/puzzle-list-energy-model-scrape-titles
