### ISSUE TITLE
Limit text length displayed in a message?

### ISSUE THREAD

**Issue by agarg5** [eternagame/eternagame.org#116]
@sharife @luxaritas On the activity feed page, we were previously limiting the number of lines of text that can appear in a message.
![image](https://user-images.githubusercontent.com/45175645/82196308-d1a8ca00-98f9-11ea-8b05-4ad376ceaf0a.png)

I changed this to not have that restriction.
![image](https://user-images.githubusercontent.com/45175645/82196231-bb027300-98f9-11ea-95e9-c52a32987290.png)

We could change this to have a `readmore` button like on the lab page
![image](https://user-images.githubusercontent.com/45175645/82196379-e7b68a80-98f9-11ea-8504-0d11b6bd89f6.png)
or something simpler like [this](https://www.npmjs.com/package/vue-read-more):
![image](https://user-images.githubusercontent.com/45175645/82196474-06b51c80-98fa-11ea-97ef-150611a2e09f.png)

**Comment by luxaritas** [comment]
I don't think this is necessary
