### ISSUE TITLE
Dropdown Links on Mobile Sidebar don't work

### ISSUE THREAD

**Issue by akrolsmir** [eternagame/eternagame.org#119]
Clicking on these don't create a dropdown as expected.

![](https://i.imgur.com/TuvoYlZ.png)

**Comment by guyguy2001** [comment]
I can't reproduce this. Which OS/Browser were you on?

**Comment by akrolsmir** [comment]
Ah, I think @agarg5 already fixed this in https://github.com/eternagame/eternagame.org/commit/9044e61f25df415c818167c897dd65eb0de18717. Thanks!
