### ISSUE TITLE
Labs - Progress bar - number of submissions remaining

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#127]
Quick glance showing player progress/participation before clicking "Enter Lab" button. Especially helpful when more than one lab is active. (Feature existed on legacy site.)

**Comment by luxaritas** [comment]
This is in progress - we've been waiting on some backend tweaks to support this properly (the way this was handled before doesn't work with the new site)

**Comment by luxaritas** [comment]
This has been done for a while
