### ISSUE TITLE
Icons do not bring up Mobile Sidebar on eternadev/eternagame

### ISSUE THREAD

**Issue by akrolsmir** [eternagame/eternagame.org#142]
Reproduce: Click on the blue filter icon in PuzzleExplore while on a mobile-sized device:

![](https://i.imgur.com/5IVJTZI.png)

Expected: Mobile sidebar is brought up

Saw: Mobile sidebar is brought up on local, but NOT eternadev.org or eternagame.org

**Comment by akrolsmir** [comment]
Tried building the prod version of the site locally with:

`npm run build
cd dist
python -m http.server 8020
`

And the issue is present there as well.

(Login doesn't seem to work here; I bypassed that by hardcoding loggedIn = true in NavbarCollapseContent)

With some console.log() debugging, my best guess is that `this.$vxm.mobile.showPageSidebar();` in [line 37 of SidebarPanel](https://github.com/eternagame/eternagame.org/blob/b47bae7b52e0a0839cf709dba71332bbef472b0a/src/components/Sidebar/SidebarPanel.vue#L37) is firing but is not accomplishing anything.

**Comment by akrolsmir** [comment]
Current hypothesis is that it's an issue related to a library we're using, vuex-class-component. It's currently [pegged to a version forked by Jon](https://github.com/eternagame/eternagame.org/blob/75ceaac91ca3c9fb5de464394cf235ff7de6d3ce/package.json#L80), since he made some patches. I tried updating to latest (2.3.2), but that didn't appear to solve it either.

Other users of the library have reported that latest build [doesn't have all the source changes](https://github.com/michaelolof/vuex-class-component/issues/71); I've tried compiling from source but that didn't seem to fix our issue either (though I'm not 100% confident I built it correctly).

Thinking that the most expedient solution is to just switch to a different method of messaging the Mobile Sidebar to open on that button click -- thoughts?

**Comment by agarg5** [comment]
@akrolsmir @luxaritas I changed vuex-class-component to https://www.npmjs.com/package/vuex-class-component and this didn't seem to break anything. 

> With some console.log() debugging, my best guess is that `this.$vxm.mobile.showPageSidebar();` in [line 37 of SidebarPanel]

I created https://github.com/eternagame/eternagame.org/pull/163 to remove a check which doesn't seem needed and should fix this issue. I'm unable to test as I tried first deploying this chance to dev, but it didn't reflect on eternadev for some reason. 

> (Login doesn't seem to work here; I bypassed that by hardcoding loggedIn = true in NavbarCollapseContent)
(https://github.com/eternagame/eternagame.org/blob/b47bae7b52e0a0839cf709dba71332bbef472b0a/src/components/Sidebar/SidebarPanel.vue#L37) is firing but is not accomplishing anything.

You can actually go directly to a puzzle, for example https://eternadev.org/puzzles/9957118, without logging in. Then you can click on the info icon to check if the sidebar opens

**Comment by agarg5** [comment]
related: https://github.com/eternagame/eternagame.org/issues/125

**Comment by agarg5** [comment]
@luxaritas I did not get a chance to finish this item this weekend. Might you/ were you planning to work on this soon? If not, I can look into it more tomorrow or Tuesday.

**Comment by agarg5** [comment]
@luxaritas fixed this issue
