### ISSUE TITLE
Don't show puzzle creator on puzzle info page if puzzle is not marked as made by player

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#147]
Via Omei in eternagame/website#57

**Comment by Omei** [comment]
I don't know why you would consider this to be an enhancement rather than a regression. Many puzzles entered into the database by developers (either player/dev or staff) have been, and will continue to be, done on behalf of the true creator.

**Comment by AlexHalb** [comment]
I'm pretty sure this can be closed - puzzles without a user are handled correctly (don't throw errors) and don't show a puzzle creator. [Here's an example](https://eternadev.org/puzzles/9957664)

**Comment by luxaritas** [comment]
That's not the issue - there's a separate made by player flag. For example https://eternadev.org/puzzles/20111 should not have an author attributed
