### ISSUE TITLE
Slow loading of landing page

### ISSUE THREAD

**Issue by rhiju** [eternagame/eternagame.org#187]
I'm seeing >15 second load times of landing page https://eternagame.org if I reset cache (apple-shift-R on Mac). 

Using Chrome 83.0.4103.61 on Mac OS 10.12.6

<img width="1313" alt="Screen Shot 2020-06-04 at 9 41 36 AM" src="https://user-images.githubusercontent.com/1672331/83786507-9de2d980-a647-11ea-925f-4c479ccb2ea6.png">

**Comment by AlexHalb** [comment]
This happens on Safari as well. Also, the load times are long for other pages too, but the landing page in particular.

**Comment by luxaritas** [comment]
Currently the landing page is doing all the requests for the normal homepage used when logged in - as part of what I'm currently working on (doing a first pass at revamping the networking) I've also revamped this. Also going to improve the authenticated homepage by executing all the requests in parallel as opposed to sequentially like they are now. Should help significantly

**Comment by luxaritas** [comment]
Should be resolved in the upcoming release
