### ISSUE TITLE
My submission count displays total submissions for puzzle, not my personal submissions

### ISSUE THREAD

**Issue by kimds91** [eternagame/eternagame.org#189]
I've submitted zero submissions for this puzzle, but it shows the total number of submissions, so players may not see the true number of submissions they have left or have contributed.

![image](https://user-images.githubusercontent.com/11445901/84037714-95024880-a964-11ea-8603-fc5d456c7bfd.png)

**Comment by kimds91** [comment]
When you inside the lab, it displays this correctly. So this is an issue only from the landing page/carousel. (yes I know these are two different labs, but issue is persistent everywhere for me).
![image](https://user-images.githubusercontent.com/11445901/84038038-fe825700-a964-11ea-9e42-f6d7ffb84e69.png)

**Comment by luxaritas** [comment]
That's really weird... It's working as intended for me. There's a big refactor pending, hoping that might help to clear it up

**Comment by kimds91** [comment]
I just reloaded the site and it displayed correctly--weird one-off bug perhaps? Feel free to close, I haven't heard from other players that this is an issue.

**Comment by luxaritas** [comment]
I know it was incorrect previously, so maybe you had an old version loaded or something... Will close for now
