### ISSUE TITLE
Account settings has wrong menubar

### ISSUE THREAD

**Issue by rhiju** [eternagame/eternagame.org#195]
<img width="1204" alt="Screen Shot 2020-06-23 at 9 45 46 AM" src="https://user-images.githubusercontent.com/1672331/85431453-6e343c80-b536-11ea-9716-d1641222c524.png">

1. The right-hand menu bar ('About', ...) does not do anything.  Maybe just remove the menubar.
2. I'd suggest 'Save Profile' to go to user's 'Profile' page.
3. In terms of getting to the Account Settings page, when user is logged in and goes to their 'Profile' have a menubar or button that goes to 'Account Settings' within the page.

**Comment by luxaritas** [comment]
Resolved in  0ae8898
