### ISSUE TITLE
Cryptic error message when Facebook login is unavailable (eg , Firefox tracking content blocking)

### ISSUE THREAD

**Issue by rhiju** [eternagame/eternagame.org#199]
I think this is the "continue with facebook button" -- shows up fine on Chrome but not in Firefox (I was trying private mode):
<img width="381" alt="Screen Shot 2020-06-30 at 11 49 45 AM" src="https://user-images.githubusercontent.com/1672331/86165276-f03cdc00-bac7-11ea-8b68-6a8c0eaaea28.png">

**Comment by luxaritas** [comment]
This is due to the nature of private windows in Firefox - Firefox outright blocks Facebook SDKs. I'm wondering if we can detect this and provide a more descriptive error

**Comment by Qmtfive** [comment]
This appears to have been fixed with newer versions of Firefox. Can anyone replicate it?

**Comment by luxaritas** [comment]
It does appear that even strict content blocking no longer leads to this error. Not sure if there are other situations where this behavior might occur
