### ISSUE TITLE
Fix axios typescript warning

### ISSUE THREAD

**Issue by agarg5** [eternagame/eternagame.org#22]
This issue: `subsequent property declarations must have the same type.  Property '$http' must be of type 'AxiosStatic', but here has type 'AxiosInstance'.` shows up every-time the Vue compiler builds:
![image](https://user-images.githubusercontent.com/45175645/80953585-1e6daa80-8dfc-11ea-8ba6-3203f93e5277.png)

**Comment by tolumide-ng** [comment]
I would make a PR for this before I proceed to other parts of the project
