### ISSUE TITLE
Puzzle can be created with a restriction of fewer GCs than the solution.

### ISSUE THREAD

**Issue by edderiofer** [eternagame/eternagame.org#225]
See [this puzzle](https://eternagame.org/puzzles/10196407), where I had locked 10 GCs into the puzzle when creating it, but also set a restriction of 0 GCs when publishing it.

There does not seem to be such a problem with the UGs restriction. I don't know whether this also happens with AUs.

**Comment by luxaritas** [comment]
This is being tracked here: https://github.com/eternagame/EternaJS/issues/127

There is actually already a fix, just hasn't been deployed yet. It'll go out with the next version.
