### ISSUE TITLE
Enable/adjust searching or filtering for puzzles by folding engine

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eternagame.org#270]
As an Eterna player, I am interested in being able to more directly filter and/or search puzzles by what folding engine they use.

At the time of this posting, the website lets you search for puzzles with a certain folding engine if you search by a given tag (for example, "[VRNA_2]" for Vienna2). However, I do not think this solution is as user-friendly or robust as it could be:
- This existing search methodology requires that the player knows not only what folding engines currently exist in Eterna but also what the corresponding tag would be. For example, although I know that Vienna2 is a folding engine, the fact that its tag is [VRNA_2] instead of [Vienna2] is not necessarily obvious.
- This existing search methodology seems like it could easily be disrupted. For example, for a recent switch puzzle I made, I temporarily re-edited the puzzle title to remove the [switch2.5] and [2 states] tags - I imagine something similar could be done with other tags (such as those denoting the folding engine).
- This existing search methodology relies upon keeping Vienna as the default folding engine - which may not always be the case in Future Eterna. Sure. you could go back and fix all of the titles of the Vienna puzzles to have new tags, but that does seem quite a painful prospect . . .

I don't know what the "ideal" solution is - but I do think adding some sort of functionality or adjustment to the current puzzle searcher that addresses this issue could improve the user experience.

**Comment by luxaritas** [comment]
We should totally have a filter for engine. We started the process of enhancing filters in #215, but stalled in part because I hadn't gotten the chance to add additional filters to the backend - this is one of those filters that needs to be added.

**Comment by luxaritas** [comment]
Tracking in #272 as a more wholistic issue
