### ISSUE TITLE
"Enter Lab" carousel button should go to lab page, not puzzle progression

### ISSUE THREAD

**Issue by Omei** [eternagame/eternagame.org#30]
1) For any existing player who currently has lab access, entering the lab from the main page should **not** go to the puzzle progression. It should go to some page that makes it clear what labs, if any, are currently open. 

2)It looks like that would be http://eternadev.org/labs?size=27&filters=active, in the current design, but the filter doesn't seem to be implemented.

**Comment by luxaritas** [comment]
In this case it should actually be the specific lab in the given carousel slide, not the entire lab list

**Comment by guyguy2001** [comment]
I can't seem to reproduce this. Are you talking about this button? It takes me to the lab page.
![image](https://user-images.githubusercontent.com/6932278/81960623-e8a99c80-9619-11ea-9b27-0c3b99541f00.png)

**Comment by luxaritas** [comment]
Yeah looks like this must've been resolved
