### ISSUE TITLE
Implement News Sidebar

### ISSUE THREAD

**Issue by akrolsmir** [eternagame/eternagame.org#44]

**Comment by akrolsmir** [comment]
Right now, the filters and the calendar are all just for show.

**Comment by agarg5** [comment]
@akrolsmir waiting on params to be added to endpoint:
https://app.clubhouse.io/vital-mind-media/story/303/add-date-filter-from-to-to-news-endpoint

**Comment by agarg5** [comment]
seems like the endpoint has been extended to support this: https://github.com/eternagame/website/commit/9c6932a3010eaa79579373e4d8838ed4a648c4ec

**Comment by agarg5** [comment]
@luxaritas On the news _view_ page, is the calendar applicable? 
![image](https://user-images.githubusercontent.com/45175645/82548060-010a4180-9b5b-11ea-9b82-39d74c1674e2.png)

On the news _view_ page, are the options applicable? 
![image](https://user-images.githubusercontent.com/45175645/82548105-11bab780-9b5b-11ea-927e-211e68cdfdab.png)

**Comment by agarg5** [comment]
@luxaritas @sharife  it seems the bootstrap vue calendar does not have support for specifying a date range. I'm planning to instead use https://vcalendar.io/?ref=madewithvuejs.com. Please let me know if that is not OK

**Comment by agarg5** [comment]
We can currently only filter by blogs/news.
