### ISSUE TITLE
Play/puzzles

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#55]
If default shows all puzzles, the large green check-mark indicating "completed" is visually helpful. I do like that additional filters were maintained!

**Comment by Tazzon77** [comment]
Now that cache is refreshed, I DO see green check mark....just smaller and harder to see than previous site.

**Comment by Tazzon77** [comment]
Puzzle shape does not center vertically in box.
![Shape display box](https://user-images.githubusercontent.com/16046040/81889323-3b7b4980-9571-11ea-9876-71ac9f6b8fca.png)

**Comment by Tazzon77** [comment]
Puzzle author not displayed on description page.

**Comment by luxaritas** [comment]
There’s a handful of weird caching issues - will file another ticket for that
