### ISSUE TITLE
Unable to Edit Profile Image

### ISSUE THREAD

**Issue by AndrewKaechele** [eternagame/eternagame.org#56]
18.3kb .jpg image, won't upload

**Comment by agarg5** [comment]
@ktamas77 What is the param to edit the user picture on the [edit user endpoint](https://eternagame.org/home/swagger/index.html#/user/actionEdit)?

**Comment by ktamas77** [comment]
Related BE ticket: https://app.clubhouse.io/vital-mind-media/story/804/edit-profile-endpoint-post-type-edit-seems-to-be-broken

**Comment by ktamas77** [comment]
@agarg5 , after careful debugging / evaluation & consulting with @luxaritas , we came to the conclusion that the image upload error is related only to the FE.
How to verify: Log in to the the legacy site: https://legacy.eternagame.org/web/player/268034/
Edit your profile and change your profile Image - it will work. 
The solution is to implement the same Profile Edit / Image upload mechanism in the new design as the currently working version is implemented in the legacy site.

Related PR: #153

**Comment by luxaritas** [comment]
The issue is that its getting improperly serialized. I think in order to work correctly we may need to use multipart/form-data instead of whatever it is now (www-url-form-encoded I think)

**Comment by AndrewKaechele** [comment]
I tried again on the legacy site and still not working there either.

**Comment by luxaritas** [comment]
I have also confirmed it works, so there must be a separate additional issue in your case - part of it may be that the image will be cached, so make sure to do a hard refresh after saving your profile

**Comment by AndrewKaechele** [comment]
Yes, that was it. thanks!
