### ISSUE TITLE
Play/puzzles - puzzle shape does not center in display box

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#57]
![Shape display box](https://user-images.githubusercontent.com/16046040/81891202-d544f580-9575-11ea-8649-3f89e4dda6a0.png)

**Comment by luxaritas** [comment]
I think how this should work is that the box height is the height of the image plus some padding - @sharife can you confirm?

**Comment by luxaritas** [comment]
Resolved in the next release
