### ISSUE TITLE
Player Profile - Complete list of cleared puzzles not displayed

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#62]
In addition to a sort option, a "search" feature would also be helpful here.

**Comment by luxaritas** [comment]
An arbitrary limit was added to reduce load times. This limit will be removed in the next release

**Comment by Tazzon77** [comment]
I did overheard a few players state that they much preferred the former single-spaced list with page navigation over the continuous batch loading and single page endless scroll. Not sure what that does to your CSS, but wanted to provide that additional feedback. Of course, filters and search functionality remain crucial features.
