### ISSUE TITLE
Mobile - play/puzzles - puzzle select

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#65]
This was captured from eteRNA chat (player Korosi)
![Mobile](https://user-images.githubusercontent.com/16046040/81898070-f01f6600-9585-11ea-9cd8-c0ee020f90f0.png)

**Comment by luxaritas** [comment]
Need more info on this one - I don’t know what toolbar is being referred to. I assume the puzzle issue is that there’s a puzzle link without a trailing slash somewhere, but I don’t know where exactly

**Comment by luxaritas** [comment]
I believe any issues with this have since been resolved. Please re-open if that is not the case
