### ISSUE TITLE
Feed is largely broken

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#66]
Extremely slow to load, and when it does, it shows like 2 things with incorrect data (even though more have been returned in the API request)

**Comment by luxaritas** [comment]
This must have something to do with notification types other than news/blog, because logging in as a new user it looks fine

**Comment by agarg5** [comment]
@luxaritas is this still an issue?

**Comment by agarg5** [comment]
@luxaritas please close when you are comfortable

**Comment by agarg5** [comment]
@luxaritas closing this. Please reopen if something is remaining
