### ISSUE TITLE
Facebook is not logged out when Eterna logs out

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#68]
When trying to log in from Chrome on iOS, I hit the login button, the modal pops up, then it seems that it submits itself (without any action on my part) and then it comes up with an error of “undefined query type”

**Comment by akrolsmir** [comment]
I've seen this issue on desktop too, and had it go away after clearing my browser cookies. Wild speculation is that is that it's related to the facebook auth integration/cookie -- I recall hearing someone mention that in dev standup.

**Comment by akrolsmir** [comment]
From Jonathan: we need to logout on client, this was previously handled by php script: https://github.com/eternagame/website/blob/master/backend/views/logout_view.php
