### ISSUE TITLE
Notification bell contents are incorrect

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#69]
On my main account on desktop, it’s completely blank. On a new account on desktop (I think, haven’t thoroughly tested) or either on mobile, it seems to be out of date content.

This should also be using the “combined” newsfeed query, which I don’t think it is right now

**Comment by agarg5** [comment]
Made some fixes on the bell icon to show messages and loading text. The `combinedNews` branch can be merged if needed to serve as a placeholder as it uses the “combined” newsfeed query. However, the “combined” newsfeed query currently doesn't return information about the author. Perhaps we should add that information in and then switch over.

**Comment by luxaritas** [comment]
@agarg5 I want to check if you've accounted for a couple things:
- Replies to private messages should be threaded under the original message, not displayed as different items in the feed
- There are additional notification types than just news/blog and direct messages - I'll probably need to help track all of the individual cases down...

**Comment by agarg5** [comment]
@luxaritas I think we misunderstood the part about message threads. I will go ahead and fix how message replies are displayed on the feed page. How should messages replies be displayed if at all on the notifications icon?

**Comment by luxaritas** [comment]
Ah, those are different - they should just show sequentially with no threading in the notification bell

**Comment by agarg5** [comment]
@luxaritas could you please send me (agarg5) another personal message without a reply and another with a reply on a reply? I want to see how the data returned differs

**Comment by luxaritas** [comment]
@agarg5 On dev or prod?

**Comment by agarg5** [comment]
@luxaritas I pushed a fix (to eternadev) to order the items in the notifications dropdown correctly as well as add only the latest reply for a message thread. Still waiting on https://app.clubhouse.io/vital-mind-media/story/314/add-user-data-in-newsfeed before being able to display associated user information for the user who wrote article

**Comment by agarg5** [comment]
@luxaritas dev

**Comment by luxaritas** [comment]
I don't think we want only the last message in the thread for the bell. Imagine that you have a message at 12:00, a news post at 1:00, a message reply at 2:00, two more news posts at 3:00 and 3:20, then another reply at 4:00. The bell should look like:
- 4:00 reply
- 3:20 article
- 3:00 article
- 2:00 reply
- 1:00 article

**Comment by agarg5** [comment]
Hi Jonathan,

Thanks I will make this change.

Thanks,
Abhi

**Comment by agarg5** [comment]
@ktamas77 just wanted to gently follow-up about the previous. Please close this issue if the answer is yes

**Comment by ktamas77** [comment]
The answer is **yes** - all objects ordered on the same timeline when using a combined endpoint, exactly as you described (timestamp is the primary key to order the objects, regardless of their types (news, blogs, comment, etc)).

**Comment by ktamas77** [comment]
https://eternagame.org/get/?type=newsfeed&combined=true&filter=all

in the `entries` array, the `timestamp` field is decreasing in the sequence, regardless of object type. the latest one is always on top.
