### ISSUE TITLE
Leaderboard 30 day and synthesized not updating

### ISSUE THREAD

**Issue by jnicol4** [eternagame/eternagame.org#70]
The 30 day leaderboard is only accumulating points, it does not reset for 30 days. (ie. the ?filter=update no longer works.

The synthesized leaderboard does not display the number synthesized, and the number is not updating.

**Comment by agarg5** [comment]
@luxaritas this is the current mapping for the [endpoint](https://ktamas77.eternagame.org/home/swagger/index.html#/user/get_get__type_users). Let's talk during the meeting about which ones need be changed?Which of these must be changed?   

   { value: 'active', text: 'side-panel-options:points-last-30-days' },
    { value: 'point', text: 'side-panel-options:total-points' },
   { value: 'synthesizes', text: 'side-panel-options:total-synthesized' },
   { value: 'update', text: 'side-panel-options:synthesized-latest' },

**Comment by agarg5** [comment]
@luxaritas just wanted to gently follow-up?

**Comment by luxaritas** [comment]
Sorry, missed this. RE: The synthesis count, I already fixed that. As far as the 30 day leaderboard, that's a backend issue

**Comment by luxaritas** [comment]
(Also, the "update" type is a magic value that triggers a cron job, it's not an actual filter)

**Comment by agarg5** [comment]
@luxaritas @ktamas77 what is remaining on this issue if anything?

**Comment by luxaritas** [comment]
Looks like this has been resolved
