### ISSUE TITLE
Chat is cut off on mobile

### ISSUE THREAD

**Issue by sharife** [eternagame/eternagame.org#71]
The website full page chat displays different font sizes in different channels, with the default general channel going off screen.

![image](https://user-images.githubusercontent.com/700596/81954041-3a700980-95bd-11ea-8220-c9952790eeb7.png)
![image](https://user-images.githubusercontent.com/700596/81954120-51aef700-95bd-11ea-8a3f-cce5bc5db9ee.png)
![image](https://user-images.githubusercontent.com/700596/81954142-583d6e80-95bd-11ea-8b80-c343b85b4fea.png)

**Comment by agarg5** [comment]
@aminere I'm closing this issue. Please re-open if it is not complete
