### ISSUE TITLE
Various caching issues

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#72]
There are a ton of issues right now with pages having improper data, namely when navigating between pages. For some reason it seems like both 1) component state isn’t getting cleared when components get removed and readded and 2) fresh requests aren’t always being made when navigating back to a page you’ve previously visited

**Comment by agarg5** [comment]
Update: had meeting about fix and documented needed changes in https://github.com/eternagame/eternagame.org/issues/134
