### ISSUE TITLE
Quest progress bar color is too similar to the background

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#73]

**Comment by luxaritas** [comment]
@sharife  color suggestion?

**Comment by sharife** [comment]
Following the comps, these should have a dark background with a light blue progress indicator.
<img width="437" alt="Screen Shot 2020-05-14 at 9 21 23 AM" src="https://user-images.githubusercontent.com/700596/81959558-807c9b80-95c4-11ea-96b6-cb069fe79115.png">
