### ISSUE TITLE
Quest progress bar color should change to competed with checkmark when 100% completed on quest detail page

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#74]

**Comment by luxaritas** [comment]
@sharife  thoughts on colors for this one too?

**Comment by sharife** [comment]
The progress bar is replaced by the "completed" text with the checkmark icon.

**Comment by luxaritas** [comment]
Ah, that’s not happening on the quest detail page

**Comment by agarg5** [comment]
should be fixed now
