### ISSUE TITLE
Add descriptions for quests which don’t have them yet

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#75]

**Comment by rhiju** [comment]
Would be great to set up Drupal edit pages for quests, could be super basic.

In the future, a GUI for quests/collection creation _by players_. @sharife has comps

**Comment by luxaritas** [comment]
The entire achievement system would need to be overhauled to support this - it's all completely hardcoded. For various reasons it is probably also better to keep it that way due to the way that the code interacts with them, but it needs some additional thought. Also as per previous discussion, I feel pretty strongly that players should be able to create collections, but only staff would create achievements (ie, tied to badges) still. A quest is just a specific class of achievement which is something that a player can take a specific action to earn (eg, Eternacon attendance is an achievement but not a quest, however solving the Eterna100 is an achievement which is categorized as a quest)
