### ISSUE TITLE
Lab pages should use lab-related images for header backgrounds

### ISSUE THREAD

**Issue by sharife** [eternagame/eternagame.org#78]
The background on the top module of the lab detail page should match the image from the homepage carousel. Looks like these images are not yet dynamic; this lab below should have the COVID-19 background.

<img width="883" alt="Screen Shot 2020-05-14 at 9 33 23 AM" src="https://user-images.githubusercontent.com/700596/81960696-3399c480-95c6-11ea-91ba-9a67add56168.png">

If there is no image associated with a lab, use the regular blue background and reduce the height of the module accordingly.

**Comment by luxaritas** [comment]
@sharife For those that do not have a banner image, could you provide a default? Also, perhaps we should have ones for OpenTB and opencrispr since those are big challenges?

**Comment by luxaritas** [comment]
I assume we don’t want to use the old “thumbnail” image for any of the old labs, even though that will mean that most of them will look the same

**Comment by sharife** [comment]
Good idea @luxaritas I'll provide a default image, as well as header images for OpenTB and OpenCRISPR.
