### ISSUE TITLE
Inconsistent layout in comment module

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eternagame.org#89]
EG https://eternagame.org/labs/9874218
![image](https://user-images.githubusercontent.com/18635705/82003655-e3a31800-962e-11ea-955f-54674a1f6ab6.png)

**Comment by akrolsmir** [comment]
Hm, browser/os? I can't repro:

![](https://i.imgur.com/7xT5k2A.png)

**Comment by luxaritas** [comment]
@akrolsmir Firefox 76.0.1 on Linux (Manjaro/Arch)
